Repository Amsterdam/signals, pull requests merged in 2021-03, with the labels that each got.

#735 Bug/sig 3587 cbs buurt data url wrong
  api/app/signals/apps/dataset/sources/cbs.py
  api/app/signals/apps/dataset/sources/shape.py
Labels: wait with merge

#738 Cleanup health app
  api/app/signals/apps/health/urls.py
  api/app/signals/apps/health/views.py
  api/app/signals/settings/base.py
  api/app/tests/apps/health/test_endpoints.py
Labels: enhancement

#739 Cleanup + small refactor on the Signal model
  api/app/signals/apps/api/v1/fields/attachment.py
  api/app/signals/apps/api/v1/fields/signal.py
  api/app/signals/apps/api/v1/serializers/signal.py
  api/app/signals/apps/api/v1/urls.py
  api/app/signals/apps/api/v1/views/_base.py
  api/app/signals/apps/api/v1/views/signal.py
  api/app/signals/apps/reporting/csv/datawarehouse/signals.py
  api/app/signals/apps/reporting/csv/horeca.py
  api/app/signals/apps/search/documents/signal.py
  api/app/signals/apps/signals/factories/signal.py
  api/app/signals/apps/signals/migrations/0137_auto_20210303_1451.py
  api/app/signals/apps/signals/models/signal.py
  api/app/signals/apps/signals/tasks.py
  api/app/tests/apps/api/v1/test_private_signal_endpoint.py
  api/app/tests/apps/api/v1/test_public_signal_endpoint.py
  api/app/tests/apps/reporting/test_datawarehouse.py
  api/app/tests/apps/signals/test_models.py
Labels: enhancement

#734 The "view_user" permission is now mandatory to view information on the "/v1/private/users/" endpoint
  api/app/signals/apps/api/generics/permissions.py
  api/app/signals/apps/api/templates/api/swagger/openapi.yaml
  api/app/signals/apps/api/v1/urls.py
  api/app/signals/apps/users/v1/filters.py
  api/app/signals/apps/users/v1/serializers/__init__.py
  api/app/signals/apps/users/v1/serializers/user.py
  api/app/signals/apps/users/v1/views/__init__.py
  api/app/signals/apps/users/v1/views/user.py
  api/app/tests/apps/users/v1/test_users.py
Labels: enhancement, wait with merge

#748 SIG-3590
  .gitignore
  api/app/signals/apps/api/generics/validators.py
  api/app/signals/apps/api/v1/serializers/source.py
  api/app/signals/apps/api/v1/views/source.py
  api/app/signals/apps/signals/admin.py
  api/app/signals/apps/signals/factories/source.py
  api/app/signals/apps/signals/migrations/0138_source_is_active.py
  api/app/signals/apps/signals/models/source.py
  api/app/signals/settings/base.py
  api/app/tests/apps/api/v1/test_private_signal_endpoint.py
  api/app/tests/apps/api/v1/test_private_signal_endpoint_create.py
  api/app/tests/apps/signals/test_tasks.py
Labels: wait with merge

#731 use correct table/field for source lookup
  api/app/signals/apps/api/v1/filters/utils.py
  api/app/tests/apps/api/v1/test_filters.py
Labels: wait with merge

#755 add export of routing department relation
  api/app/signals/apps/reporting/csv/datawarehouse/__init__.py
  api/app/signals/apps/reporting/csv/datawarehouse/signals.py
  api/app/signals/apps/reporting/csv/datawarehouse/tasks.py
  api/app/signals/apps/reporting/management/commands/dumpcsv.py
  api/app/tests/apps/reporting/management/commands/test_command.py
Labels: wait with merge

#754 feature/SIG-3580
  api/app/signals/apps/email_integrations/admin.py
  api/app/signals/apps/email_integrations/factories.py
  api/app/signals/apps/email_integrations/mail_actions.py
  api/app/signals/apps/email_integrations/reporter_rules.py
  api/app/signals/apps/email_integrations/templates/admin/change_email_template_form.html
  api/app/signals/apps/email_integrations/templates/email/default_notification_message.txt
  api/app/signals/apps/email_integrations/templates/email/signal_created.html
  api/app/signals/apps/email_integrations/templates/email/signal_created.txt
  api/app/signals/apps/email_integrations/templates/email/signal_default.html
  api/app/signals/apps/email_integrations/templates/email/signal_default.txt
  api/app/signals/apps/email_integrations/templates/email/signal_status_changed_afgehandeld.html
  api/app/signals/apps/email_integrations/templates/email/signal_status_changed_afgehandeld.txt
  api/app/signals/apps/email_integrations/templates/email/signal_status_changed_heropend.html
  api/app/signals/apps/email_integrations/templates/email/signal_status_changed_heropend.txt
  api/app/signals/apps/email_integrations/templates/email/signal_status_changed_ingepland.html
  api/app/signals/apps/email_integrations/templates/email/signal_status_changed_ingepland.txt
  api/app/signals/apps/email_integrations/templates/email/signal_status_changed_optional.html
  api/app/signals/apps/email_integrations/templates/email/signal_status_changed_optional.txt
  api/app/signals/apps/email_integrations/utils.py
  api/app/tests/apps/email_integrations/test_email_templates.py
  api/app/tests/apps/email_integrations/test_email_templates_address_formating.py
  api/app/tests/apps/email_integrations/test_mail.py
  api/app/tests/apps/email_integrations/test_utils.py
  docker-compose.yml
Labels: enhancement
