Repository Amsterdam/signals, pull requests merged in 2021-12, with the labels that each got.

#893 feature/SIG-4610
  api/app/signals/apps/api/serializers/nested/reporter.py
  api/app/signals/apps/api/tests/test_private_signal_endpoint.py
  api/app/signals/apps/signals/migrations/0148_alter_reporter_options.py
  api/app/signals/apps/signals/models/reporter.py
  api/app/signals/apps/users/tests/v1/test_permissions.py
Labels: enhancement

#894 chore/django-3.2.10
  api/app/signals/apps/api/tests/test_signal_context_view.py
  api/requirements.txt
Labels: dependencies

#892 feature/experimental-app
  api/app/signals/apps/experimental/README.md
  api/app/signals/apps/experimental/__init__.py
  api/app/signals/apps/experimental/apps.py
  api/app/signals/apps/experimental/migrations/0001_initial.py
  api/app/signals/apps/experimental/migrations/__init__.py
  api/app/signals/apps/experimental/models/__init__.py
  api/app/signals/apps/experimental/models/querysets.py
  api/app/signals/apps/experimental/models/signals_filter_view.py
  api/app/signals/apps/experimental/rest_framework/__init__.py
  api/app/signals/apps/experimental/rest_framework/filters/__init__.py
  api/app/signals/apps/experimental/rest_framework/filters/signal.py
  api/app/signals/apps/experimental/rest_framework/serializers/__init__.py
  api/app/signals/apps/experimental/rest_framework/serializers/signal.py
  api/app/signals/apps/experimental/rest_framework/urls.py
  api/app/signals/apps/experimental/rest_framework/viewsets/__init__.py
  api/app/signals/apps/experimental/rest_framework/viewsets/signal.py
  api/app/signals/apps/experimental/tests/__init__.py
  api/app/signals/apps/experimental/tests/test_experimental_private_signal_endpoint.py
  api/app/signals/apps/experimental/tests/test_filters.py
  api/app/signals/apps/signals/migrations/0042_auto_new_history_db_view.py
  api/app/signals/apps/users/migrations/0004_auto_20191106_0837.py
  api/app/signals/settings/base.py
  api/app/signals/urls.py
Labels: enhancement

#897 add note export to csv
  api/app/signals/apps/reporting/csv/datawarehouse/__init__.py
  api/app/signals/apps/reporting/csv/datawarehouse/signals.py
  api/app/signals/apps/reporting/csv/datawarehouse/tasks.py
  api/app/signals/apps/reporting/management/commands/dumpcsv.py
  api/app/signals/apps/reporting/tests/csv/test_datawarehouse.py
  api/app/signals/apps/reporting/tests/management/commands/test_command.py
Labels: wait with merge

#900 fix/SIG-4258
  api/app/signals/urls.py
Labels: bug
