Repository Amsterdam/signals, pull requests merged in 2021-02, with the labels that each got.

#704 Make JWKS setting secure by default
  api/app/signals/settings/base.py
  api/app/signals/settings/development.py
Labels: bug

#703 feature/SIG-3496
  api/app/signals/apps/email_integrations/templatetags/location.py
  api/app/signals/apps/signals/models/__init__.py
  api/app/signals/apps/signals/models/location.py
  api/app/signals/apps/signals/utils/location.py
  api/app/signals/settings/base.py
  api/app/tests/apps/email_integrations/reporter/test_email_templates_address_formating.py
  api/app/tests/apps/signals/test_utils.py
Labels: enhancement

#707 feature/SIG-3501
  api/app/signals/apps/email_integrations/admin.py
Labels: enhancement

#710 fix/test-email-address-formatting
  api/app/tests/apps/email_integrations/reporter/test_email_templates_address_formating.py
Labels: bug

#717 fix/bug-in-AddressFormatter
  api/app/signals/apps/signals/utils/location.py
  api/app/tests/apps/signals/test_utils.py
Labels: bug

#685 Use area_code fallback when stadsdeel is unknown during csv export
  api/app/signals/apps/reporting/csv/datawarehouse/locations.py
Labels: wait with merge

#708 Bugfix/area code should be multiple choice
  api/app/signals/apps/api/v1/filters/signal.py
Labels: wait with merge

#719 SIG-3510 add image filetype check to Sigmax PDF rendering
  api/app/signals/apps/api/templates/api/pdf/print_signal.html
  api/app/signals/apps/api/v1/views/pdf.py
  api/app/signals/apps/services/domain/images.py
  api/app/signals/apps/sigmax/stuf_protocol/outgoing/pdf.py
  api/app/tests/apps/api/v1/test_pdf.py
  api/app/tests/apps/services/__init__.py
  api/app/tests/apps/services/domain/__init__.py
  api/app/tests/apps/services/domain/images.py
Labels: wait with merge
