Repository Amsterdam/signals, pull requests merged in 2021-11, with the labels that each got.

#868 SIG-3988 Performance refactor of the private/signals/geography endpoint
  api/app/signals/apps/api/app_settings.py
  api/app/signals/apps/api/generics/pagination.py
  api/app/signals/apps/api/serializers/__init__.py
  api/app/signals/apps/api/serializers/signal.py
  api/app/signals/apps/api/views/signal.py
  api/app/signals/apps/signals/models/aggregates/__init__.py
  api/app/signals/apps/signals/models/aggregates/json_agg.py
  api/app/signals/apps/signals/models/functions/__init__.py
  api/app/signals/apps/signals/models/functions/asgeojson.py
  api/app/tests/apps/api/test_private_signal_endpoint.py
Labels: enhancement, refactor

#889 Refactored the ExtraPropertiesValidator and added unit tests
  api/app/signals/apps/api/tests/__init__.py
  api/app/signals/apps/api/tests/validators/__init__.py
  api/app/signals/apps/api/tests/validators/test_extra_properties.py
  api/app/signals/apps/api/validators/extra_properties.py
Labels: refactor

#890 feature/email-template-admin-tweaks
  api/app/signals/apps/email_integrations/admin.py
  api/app/signals/apps/email_integrations/templates/admin/change_email_template_form.html
  api/app/signals/apps/email_integrations/templates/markdownx/widget.html
  api/app/signals/apps/email_integrations/utils.py
  api/app/signals/settings/base.py
  api/app/signals/urls.py
  api/requirements.txt
Labels: enhancement

#874 propagate session_service to serializers
  api/app/signals/apps/questionnaires/rest_framework/serializers.py
  api/app/signals/apps/questionnaires/rest_framework/views/public.py
  api/app/signals/apps/questionnaires/tests/rest_framework/views/test_public_sessions_endpoint.py
Labels: wait with merge
