Repository Amsterdam/signals, pull requests merged in 2022-01, with the labels that each got.

#902 SIG-4196-Remove map_select from question types
  api/app/signals/apps/signals/migrations/0149_alter_question_field_type.py
  api/app/signals/apps/signals/models/question.py
Labels: help wanted, wait with merge

#901 feature/SIG-4175
  api/app/signals/apps/api/fields/category.py
  api/app/signals/apps/api/fields/extra_properties.py
  api/app/signals/apps/api/serializers/category.py
  api/app/signals/apps/api/serializers/signal.py
  api/app/signals/apps/api/templates/api/swagger/openapi.yaml
  api/app/signals/apps/api/tests/json_schema/get_signals_v1_public_terms_categories.json
  api/app/signals/apps/api/tests/json_schema/get_signals_v1_public_terms_categories_{slug}.json
  api/app/signals/apps/api/tests/json_schema/get_signals_v1_public_terms_categories_{slug}_sub_categories_{sub_slug}.json
  api/app/signals/apps/api/tests/test_private_signal_endpoint_create.py
  api/app/signals/apps/api/tests/test_public_category_endpoint.py
  api/app/signals/apps/api/tests/test_public_signal_endpoint.py
  api/app/signals/apps/questionnaires/rest_framework/fields.py
  api/app/signals/apps/questionnaires/tests/rest_framework/json_schema/public_get_questionnaire_detail.json
  api/app/signals/apps/questionnaires/tests/rest_framework/json_schema/public_get_questionnaire_list.json
  api/app/signals/apps/questionnaires/tests/rest_framework/views/public/test_public_questionnaires_endpoint.py
  api/app/signals/apps/questionnaires/tests/rest_framework/views/public/test_public_questions_endpoint.py
  api/app/signals/apps/questionnaires/tests/rest_framework/views/public/test_public_sessions_endpoint.py
  api/app/signals/apps/questionnaires/tests/rest_framework/views/public/test_reaction_request_flow.py
  api/app/signals/apps/signals/factories/category.py
  api/app/signals/apps/signals/managers.py
  api/app/signals/apps/signals/migrations/0150_category_questionnaire.py
  api/app/signals/apps/signals/models/category.py
Labels: enhancement, help wanted

#915 bugfix/attachment-image-DecompressionBombError
  api/app/signals/apps/api/serializers/attachment.py
  api/app/signals/apps/api/tests/test_filescanner.py
  api/app/signals/apps/services/domain/filescanner.py
Labels: bug
