Repository Amsterdam/signals, pull requests merged in 2022-03, with the labels that each got.

#942 feature/SIG-4430
  api/app/signals/apps/email_integrations/actions/abstract.py
  api/app/signals/apps/email_integrations/exceptions.py
  api/app/signals/apps/email_integrations/tests/test_actions.py
  api/app/signals/apps/email_integrations/tests/test_utils.py
  api/app/signals/apps/email_integrations/utils.py
Labels: enhancement

#937 Expose created_by in attachment serializer, copy created_by correctly…
  api/app/signals/apps/api/serializers/__init__.py
  api/app/signals/apps/api/serializers/attachment.py
  api/app/signals/apps/api/serializers/signal.py
  api/app/signals/apps/api/templates/api/swagger/openapi.yaml
  api/app/signals/apps/api/tests/test_private_signal_endpoint.py
  api/app/signals/apps/services/domain/auto_create_children/actions.py
  api/app/signals/apps/signals/managers.py
Labels: wait with merge

#939 Feature/attachments public upload state checks
  api/app/signals/apps/api/serializers/attachment.py
  api/app/signals/apps/api/tests/test_public_signal_endpoint.py
Labels: wait with merge

#947 bug/SIG-4458
  api/app/signals/apps/api/serializers/email_preview.py
  api/app/signals/apps/api/templates/api/swagger/openapi.yaml
  api/app/signals/apps/api/tests/test_private_signal_email_preview_endpoint.py
  api/app/signals/apps/api/views/signals/private/signals.py
Labels: bug

#958 SIG-4510 Status update to "reaction requested" should allow 400 characters instead of 200
  api/app/signals/apps/api/serializers/nested/status.py
  api/app/signals/apps/api/tests/test_reaction_request_flow_trigger.py
  api/app/signals/apps/email_integrations/tests/test_actions.py
  api/app/signals/apps/email_integrations/tests/test_rules.py
  api/app/signals/apps/questionnaires/migrations/0008_auto_20220329_1929.py
  api/app/signals/apps/questionnaires/models/question.py
  api/app/signals/apps/questionnaires/services/reaction_request.py
Labels: bug
