Repository Amsterdam/signals, pull requests merged in 2022-10, with the labels that each got.

#1082 Bumped Django 3.2.16
  api/requirements.txt
Labels: dependencies

#1083 Use the first item from the text_list as text if empty
  api/app/signals/apps/reporting/csv/datawarehouse/kto_feedback.py
  api/app/signals/apps/reporting/tests/csv/test_feedback_text_or_text_list.py
Labels: bug

#1085 Refactored the Health app to contain all rest code in the "rest_frame…
  api/app/signals/apps/health/rest_framework/__init__.py
  api/app/signals/apps/health/rest_framework/views.py
  api/app/signals/apps/health/tests/rest_framework/__init__.py
  api/app/signals/apps/health/tests/rest_framework/test_endpoints.py
  api/app/signals/apps/health/urls.py
Labels: refactor

#1086 Refactored the Search app to contain all rest code in the "rest_framework" folder
  api/app/signals/apps/api/urls.py
  api/app/signals/apps/search/rest_framework/__init__.py
  api/app/signals/apps/search/rest_framework/pagination.py
  api/app/signals/apps/search/rest_framework/views.py
  api/app/signals/apps/search/urls.py
Labels: refactor

#1088 Refactored the Feedback app to contain all rest code in the "rest_framework" folder
  api/app/signals/apps/api/urls.py
  api/app/signals/apps/feedback/rest_framework/__init__.py
  api/app/signals/apps/feedback/rest_framework/exceptions.py
  api/app/signals/apps/feedback/rest_framework/serializers.py
  api/app/signals/apps/feedback/rest_framework/views.py
  api/app/signals/apps/feedback/routers.py
  api/app/signals/apps/feedback/tests/rest_framework/__init__.py
  api/app/signals/apps/feedback/tests/rest_framework/test_feedback.py
  api/app/signals/apps/feedback/tests/rest_framework/test_serializer.py
Labels: refactor

#1090 Added AzureStorage as a configurable storage. It is now possible to use
  api/app/signals/apps/reporting/csv/utils.py
  api/app/signals/apps/reporting/management/commands/dump_tdo_csv_files.py
  api/app/signals/apps/reporting/management/commands/dump_test_csv.py
  api/app/signals/apps/reporting/management/commands/dumpcsv.py
  api/app/signals/apps/reporting/models/export.py
  api/app/signals/apps/reporting/tests/csv/test_datawarehouse.py
  api/app/signals/apps/reporting/utils.py
  api/app/signals/settings/base.py
  api/requirements.txt
  docker-compose.yml
Labels: enhancement

#1091 Added Azure Application Insights for logging
  api/app/logs/__init__.py
  api/app/signals/apps/email_integrations/tests/test_actions.py
  api/app/signals/settings/base.py
  api/requirements.txt
  api/requirements/req-base.txt
  docker-compose.yml
Labels: enhancement

#1094 Updated the ci.yml from ubuntu-18.04 to ubuntu-20.04
  .github/workflows/ci.yml
Labels: dependencies

#1093 Adding authentication to the "My Signals" app
  api/app/signals/apps/email_integrations/migrations/0006_alter_emailtemplate_key.py
  api/app/signals/apps/email_integrations/models.py
  api/app/signals/apps/email_integrations/templates/admin/change_email_template_form.html
  api/app/signals/apps/my_signals/README.md
  api/app/signals/apps/my_signals/admin.py
  api/app/signals/apps/my_signals/app_settings.py
  api/app/signals/apps/my_signals/factories.py
  api/app/signals/apps/my_signals/mail.py
  api/app/signals/apps/my_signals/management/__init__.py
  api/app/signals/apps/my_signals/management/commands/__init__.py
  api/app/signals/apps/my_signals/management/commands/cleanup_expired_my_signal_tokens.py
  api/app/signals/apps/my_signals/migrations/0001_initial.py
  api/app/signals/apps/my_signals/migrations/__init__.py
  api/app/signals/apps/my_signals/models.py
  api/app/signals/apps/my_signals/rest_framework/authentication.py
  api/app/signals/apps/my_signals/rest_framework/serializers/token.py
  api/app/signals/apps/my_signals/rest_framework/throttling.py
  api/app/signals/apps/my_signals/rest_framework/utils.py
  api/app/signals/apps/my_signals/rest_framework/views/signals.py
  api/app/signals/apps/my_signals/rest_framework/views/token.py
  api/app/signals/apps/my_signals/tasks.py
  api/app/signals/apps/my_signals/templates/my_signals/swagger/public_openapi.yaml
  api/app/signals/apps/my_signals/tests/management/__init__.py
  api/app/signals/apps/my_signals/tests/management/commands/__init__.py
  api/app/signals/apps/my_signals/tests/management/commands/test_cleanup_expired_my_signal_tokens.py
  api/app/signals/apps/my_signals/tests/rest_framework/views/test_my_signals_detail.py
  api/app/signals/apps/my_signals/tests/rest_framework/views/test_my_signals_history.py
  api/app/signals/apps/my_signals/tests/rest_framework/views/test_my_signals_list.py
  api/app/signals/apps/my_signals/tests/rest_framework/views/test_token.py
  api/app/signals/apps/my_signals/tests/test_mail.py
  api/app/signals/apps/my_signals/tests/test_task.py
  api/app/signals/apps/my_signals/urls.py
  api/app/signals/settings/base.py
Labels: enhancement

#1097 Cast AZURE_STORAGE_URL_EXPIRATION_SECS to integer
  api/app/signals/settings/base.py
Labels: wait with merge

#1100 Refactored the docker-compose.yml
  docker-compose.yml
  docker-compose/environments/.api
  docker-compose/environments/.celery
  docker-compose/environments/.celery_beat
  docker-compose/scripts/initialize.sh
  docs/topics/dummy-data.md
Labels: refactor
