Repository Amsterdam/signals, pull requests merged in 2022-12, with the labels that each got.

#1071 Update Standard for Public Code assessment v.0.4.0
  docs/topics/signalen-and-standard-for-public-code.md
Labels: help wanted

#1120 Run routing expressions on signal location or category change
  api/app/signals/apps/signals/admin/expression.py
  api/app/signals/apps/signals/models/routing_expression.py
  api/app/signals/apps/signals/signal_receivers.py
  api/app/signals/apps/signals/tests/test_signal_receivers.py
  api/app/signals/settings/feature_flags.py
Labels: enhancement

#1128 Refactor slow performing "V1 public signals geography" endpoint
  api/app/signals/apps/api/filters/signal.py
  api/app/signals/apps/api/tests/test_public_signal_geography_endpoint.py
  api/app/signals/apps/api/views/signals/public/signals.py
  api/app/signals/apps/signals/migrations/0164_materialized_view_public_signals_geography_feature_collection.py
  api/app/signals/apps/signals/models/views/__init__.py
  api/app/signals/apps/signals/models/views/signal.py
  api/app/signals/apps/signals/tasks.py
Labels: bug, refactor
